import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Art of Lasting Love",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative bg-cover bg-no-repeat bg-fixed bg-center overflow-x-hidden antialiased ${geistSans.variable} ${geistMono.variable}`}
        style={{ backgroundImage: "url('/trees.png')" }}
      >
        <div className="absolute inset-0 bg-purple-900/50 z-[-1]" />

        <Navbar />
        {children}
        <footer className="text-center py-8 bg-black text-gray-400">
          <p>
            © {new Date().getFullYear()} Art Of Lastin Love. All rights
            reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
